### ISSUE TITLE
Don't work!

### ISSUE THREAD

**Issue by Artyom16RUS** [Artyom16RUS/WebApp#1]
![image](https://user-images.githubusercontent.com/8596653/69857567-48e19780-12a1-11ea-87dd-2d3df33daadc.png)

![image](https://user-images.githubusercontent.com/8596653/69857906-ed63d980-12a1-11ea-80b1-76f88d55d5a3.png)

Какая то проблема с путем контекст. В интеренете находил способы решения, но ошибка не меняется. -> [log.txt](https://github.com/Artyom16RUS/WebApp/files/3904499/log.txt)

**Comment by coursar** [comment]
Вас губят опечатки, см #2
